//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<decimal> Motor { get; set; }
        public Nullable<int> Price { get; set; }
        public string Type { get; set; }
        public Nullable<int> MarkaID { get; set; }
    
        public virtual Marka Marka { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
